# fly.toml app configuration file generated for datingappbyhradyska on 2023-11-30T18:40:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappbyhradyska"
primary_region = "waw"

[build]
  image = "hradyska/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="drrowuzlh"
  CloudinarySettings__ApiKey="192185259879951"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
